DROP TABLE user_profile;
CREATE TABLE user_profile (
id VARCHAR(36) NOT NULL PRIMARY KEY,
forename TINYTEXT NOT NULL,
surname TINYTEXT NOT NULL,
email TINYTEXT NOT NULL,
city TINYTEXT NOT NULL,
user_name TINYTEXT NOT NULL,
password TINYTEXT NOT NULL
);